# Generated by Django 4.2.2 on 2023-06-08 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('releaseYear', models.IntegerField()),
                ('publisher', models.CharField(max_length=120)),
                ('logoUrl', models.CharField(max_length=480)),
            ],
        ),
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.game')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.tag')),
            ],
        ),
    ]
